#!/usr/bin/env python3

from argparse import ArgumentParser
from maglev import start_server, RouterMiddleware, LoggerMiddleware, routing_plugin_pages
from pathlib import Path

parser = ArgumentParser()
parser.add_argument("--dir", action="store", default=str(Path.cwd()))
parser.add_argument("--multi-process",
                    action="store_true",
                    help="Calculates the number of CPUs on the computer and creates a process for each. This will make the server faster, but will take up more computer resources.")
args = parser.parse_args()

DIR = Path(args.dir)
MULTI_PROCESS = args.multi_process
MIDDLEWARE_PLUGINS = [
    RouterMiddleware([
        routing_plugin_pages(DIR / "pages")
    ]),
    LoggerMiddleware()
]
start_server(MIDDLEWARE_PLUGINS, multi_process=MULTI_PROCESS)
